"""Pauli operators, eigenstates and teleportation correction rules.

Mathematical background
-----------------------
The single-qubit Pauli group is generated by

    I = [[1, 0], [0, 1]]        X = [[0, 1], [1, 0]]
    Y = [[0, -i], [i, 0]]       Z = [[1, 0], [0, -1]]

Each non-identity Pauli operator has two eigenstates with eigenvalues +/-1:

    Z: |0>, |1>                          (computational basis)
    X: |+> = (|0>+|1>)/sqrt(2),  |-> = (|0>-|1>)/sqrt(2)
    Y: |+i> = (|0>+i|1>)/sqrt(2), |-i> = (|0>-i|1>)/sqrt(2)

A message bit is encoded into one of these eigenstates.  Because eigenstates of
*different* Pauli operators are mutually unbiased -- |<+|0>|^2 = 1/2 -- an
attacker who measures in the wrong basis obtains a uniformly random outcome and
unavoidably disturbs the state (a direct consequence of the no-cloning theorem).
That disturbance is exactly what the threshold engine detects.

Teleportation correction rule
-----------------------------
After Alice's Bell measurement yields the two classical bits (m1, m0), the
receiver restores the teleported state with

    (m1, m0) = (0, 0) -> I        (0, 1) -> X
    (1, 0) -> Z                   (1, 1) -> ZX  (== Y up to a global phase)

`correction_for` implements this lookup table.
"""

from __future__ import annotations

from typing import Dict, List, Tuple

import numpy as np

#: Bases in which a message bit can be encoded / measured.
PAULI_BASES: Tuple[str, ...] = ("X", "Y", "Z")

#: Matrix representation of the single-qubit Pauli group generators.
PAULI_MATRICES: Dict[str, np.ndarray] = {
    "I": np.array([[1, 0], [0, 1]], dtype=complex),
    "X": np.array([[0, 1], [1, 0]], dtype=complex),
    "Y": np.array([[0, -1j], [1j, 0]], dtype=complex),
    "Z": np.array([[1, 0], [0, -1]], dtype=complex),
}


def correction_for(m1: int, m0: int) -> str:
    """Return the Pauli correction label for Bell-measurement outcome (m1, m0).

    ``m1`` is the outcome of Alice's *message* qubit measured in the X basis
    (after the CNOT + H of the Bell measurement) and ``m0`` the outcome of her
    half of the EPR pair.  The returned label is one of ``I``, ``X``, ``Z``,
    ``Y`` where ``Y`` stands for the ``Z X`` product (equal to ``Y`` up to the
    physically irrelevant global phase ``i``).
    """
    table = {(0, 0): "I", (0, 1): "X", (1, 0): "Z", (1, 1): "Y"}
    return table[(int(m1) & 1, int(m0) & 1)]


def eigenstate_angles(basis: str, bit: int) -> Tuple[float, float, float]:
    """Return Euler angles (theta, phi, lam) preparing a Pauli eigenstate.

    The returned angles are meant for Qiskit's ``u(theta, phi, lam)`` gate and
    prepare the ``+1`` eigenstate for ``bit == 0`` and the ``-1`` eigenstate for
    ``bit == 1``:

        Z basis -> |0>, |1>
        X basis -> |+>, |->
        Y basis -> |+i>, |-i>
    """
    basis = basis.upper()
    if basis == "Z":
        return (np.pi, 0.0, np.pi) if bit else (0.0, 0.0, 0.0)
    if basis == "X":
        # |+> = U(pi/2, 0, pi)|0>, |-> = U(pi/2, pi, pi)|0>
        return (np.pi / 2, np.pi if bit else 0.0, np.pi)
    if basis == "Y":
        # |+i> = U(pi/2, pi/2, pi)|0>, |-i> = U(pi/2, -pi/2, pi)|0>
        return (np.pi / 2, -np.pi / 2 if bit else np.pi / 2, np.pi)
    raise ValueError(f"unknown Pauli basis: {basis!r}")


def basis_schedule(key_bits: List[int], length: int) -> List[str]:
    """Derive the per-position measurement bases from shared key material.

    Two key bits select one of three Pauli bases; the mapping is deterministic
    so that Alice and Bob agree on the schedule, but unpredictable to anybody
    who does not hold the key.
    """
    bases: List[str] = []
    for i in range(length):
        a = key_bits[(2 * i) % len(key_bits)]
        b = key_bits[(2 * i + 1) % len(key_bits)]
        bases.append(PAULI_BASES[(2 * a + b) % 3])
    return bases
